---

# Config file for envoy-logger

# Your login info for enphaseenergy.com
enphaseenergy:
  email: name@example.com
  password: mypassword123

# Information about your specific Envoy instance.
# https://enlighten.enphaseenergy.com will report the serial number under the "IQ-Gateway" information
envoy:
  serial: 123456789012
  url: https://envoy.local

  # Give your envoy a name.
  # All points logged will be tagged with "source=<tag>"
  # Useful if you have multiple envoys
  tag: power-meter

# How to access InfluxDB
influxdb:
  url: http://localhost:8086
  token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  org: home

  # Which InfluxDB bucket to send measurements.
  # This can be useful to control different data-retention rules
  # alternatively use the "bucket" key if you want everything to be sent to the
  # same bucket
  bucket_hr: envoy_high_rate
  bucket_lr: envoy_low_rate
  # bucket: envoy_all_data

# How to access Prometheus
prometheus:
  # Change this to an open port on the host that is running envoy-logger
  # Then configure a scraper in prometheus.yml with the hostname and port of the host running envoy-logger
  listening_port: 1234

# Since the Envoy only tracks panel-level inverter production by serial number,
# it can be useful to provide InfluxDB measurements with additional tags that
# further describe your panels. This is completely optional, but can be useful
# metadata for your dashboard.
# You can figure out which inverter is which by logging into https://enlighten.enphaseenergy.com/
# and viewing: https://enlighten.enphaseenergy.com/pv/systems/<account number>/array_layout_x.json
# This will contain the X/Y coordinates of each inverter/panel.
# Since my layout is pretty simple, I chose to tag them with simple row/column numbers.
# Up to you to define a labeling scheme that works for you.
inverters:
  # This is the inverter's serial number. NOT the inverter ID, module ID, or SKU as displayed in some places
  "202212345600":
    tags:
      row: 1
      col: 1
  "202212345601":
    tags:
      row: 1
      col: 2
  "202212345602":
    tags:
      row: 2
      col: 1
  "202212345603":
    tags:
      row: 2
      col: 2
