name: Docker Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run linter checkers
      run: ./test.sh

    - name: Build the Docker image
      run: docker build
        -t docker.io/jasonajack/envoy-logger:$(date +%s)
        -t docker.io/jasonajack/envoy-logger:latest
        .
